version: '3.9'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mysqldb
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: patients
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 3000
    volumes:
      - $HOME/nodeapp/:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
